cassandra:
  image: openzipkin/zipkin-cassandra:1.23.1
  ports:
    - 9042:9042
# The collector process is used for legacy zipkin instrumentation, which log via
# scribe. It can also poll kafka, when the KAFKA_ZOOKEEPER variable is set.
collector:
  image: openzipkin/zipkin-collector:1.23.1
  environment:
    - TRANSPORT_TYPE=scribe
    - STORAGE_TYPE=cassandra
  expose:
    - 9410
  ports:
    - 9410:9410
    - 9900:9900
  links:
    - cassandra:storage
# The query process services the UI, and also exposes a POST endpoint that
# instrumentation can send trace data to.
query:
  image: openzipkin/zipkin-query:1.23.1
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
    - STORAGE_TYPE=cassandra
  expose:
    - 9411
  ports:
    - 9411:9411
    - 9901:9901
  links:
    - cassandra:storage
web:
  image: openzipkin/zipkin-web:1.23.1
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - query
