#spring:
#  sleuth:
#    zipkin:
#      enabled: false


logging:
  level:
    org.springframework.security: DEBUG
#security:
#  oauth2:
#    client:
#      clientId: 89630a412fa314777dc2
#      clientSecret: c7a29ec26ec7805e78b496ea67cc13e5a9b8bcf0
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://api.github.com/user
#      prefer-token-info: false
